"""初回マイグレーション

Revision ID: f88f35f2f320
Revises: 4b45c7a8d2c3
Create Date: 2025-08-08 04:25:55.649697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88f35f2f320'
down_revision = '4b45c7a8d2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # ここを修正: is_verified カラムに server_default を追加
        # server_default はデータベースレベルでのデフォルト値
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('0'))) # SQLiteは '0' or '1'

        # SQLiteのBooleanは通常0/1で表現されるため、sa.text('0') を使う
        # もしPostgreSQLなど他のDBを使う場合は、sa.false() や False が使える
        # batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false())) # 他のDBの場合

        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_verification_token', type_='unique')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
